apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::904296583975:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-OZPSH7OZHOLH
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::904296583975:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-08T08:10:01Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2023"
  uid: 9022bec5-78bf-4696-aa0e-297c73d9ed71
